### ISSUE TITLE
Feature request: support GeoJSON

### ISSUE THREAD

**Issue by jandot** [ngyewch/svelte-leaflet#1]
svelte-leaflet does make it very simple to incorporate leaflet maps in svelte. I can however not see how to load GeoJSON files. If that is not implemented yet, please consider this a feature request.

Thank you for your effort!
jandot

**Comment by ngyewch** [comment]
v0.6.0 released. Please let me know if it works for you.

**Comment by jandot** [comment]
Thank you for adding this so quickly. Trying out the example code on https://ngyewch.github.io/svelte-leaflet/components/GeoJSON I however get a map with empty and/or misplaced tiles. Does this have anything to do with GeoJSON? There are no error sent to the console.

<img width="1278" alt="mangled_leaflet" src="https://user-images.githubusercontent.com/10043/112757299-78b1c400-8fe9-11eb-8f81-7dc3028aaa58.png">

**Comment by ngyewch** [comment]
Hmm, OK that's weird, I'll look into it.

**Comment by ngyewch** [comment]
I've released v0.6.1. Please give that a try.

I have a separate standalone test app here: https://github.com/ngyewch/svelte-leaflet-test

**Comment by ngyewch** [comment]
Closed due to inactivity.
