### ISSUE TITLE
svelte.dev REPL example does not load

### ISSUE THREAD

**Issue by daxreyes** [ngyewch/svelte-leaflet#2]
Tried the example but getting

Could not load https://unpkg.com/https@1.0.0/index.js (imported by https://unpkg.com/axios@0.21.1/lib/adapters/http.js): Cannot find "/index.js" in https@1.0.0

**Comment by ngyewch** [comment]
Not quite sure why it's doing that. In the meantime, you can try https://github.com/ngyewch/svelte-leaflet-test

**Comment by ngyewch** [comment]
No longer supporting the use of the REPL.
