### ISSUE TITLE
Add support for TileLayer.WMS

### ISSUE THREAD

**Issue by DomWeldon** [ngyewch/svelte-leaflet#7]
Hello - thanks so much for creating this library. I am looking to test it out on a project I am building at work. I noticed that currently the`TileLayer` component only supports the `L.tileLayer` constructor, however, there is an additional constructor for layers using a WMS endpoint rather than the standard X,Y,Z format. I am going to create a PR to add support for this shortly. 

Would appreciate thoughts and advice on whether it can be considered for merge.

**Comment by ngyewch** [comment]
Merged, see #8
