### ISSUE TITLE
Add an example for event handlers ?

### ISSUE THREAD

**Issue by happysalada** [ngyewch/svelte-leaflet#9]
Hi Thank you for this great library!

I couldn't find a way to do event handlers on markers.
Something like
```
  <Marker {latLng} on:click={() => {
    console.log("click")
  }}>
```
will not do anything.
I briefly looked through the code of the library and saw that you have an EventBridge specifically for this. This would tend to tell me event handlers would work, however, I couldn't find how. Maybe it would be good to have an event handler example in the doc ?
I'm happy to write documentation if you show me how to make it work.

**Comment by ngyewch** [comment]
Hi, have a look at: https://ngyewch.github.io/svelte-leaflet/event-handling

You'll have to add `events={['click']}`.

Try:
```
<Marker {latLng} events={['click']} on:click={() => { console.log("click") }}>
```

**Comment by happysalada** [comment]
I can't believe, I didn't see that!
Thank you for taking the time!

**Comment by shubhendumadhukar** [comment]
I am trying to do this for the `LeafletMap` component. I am interested in `load` event which I don't seem to be able to configure.
```svelte
<LeafletMap
    bind:this={leafletMap}
    bind:options={mapOptions}
    events={["load"]}
    on:load={() => {
      console.log("load");
    }}
  >
....
</LeafletMap>
```

Note that, I tested with other events like `zoom`, `click` etc. Those work just fine.

**Comment by kauaicreative** [comment]
@shubhendumadhukar check this out https://github.com/ngyewch/svelte-leaflet/issues/31#issue-1946253693
